theme: jeklly-theme-Cayman

# Site settings
title: My GitHub Page
description: A description of my awesome GitHub Pages site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
repository: username/repository

# Build settings
markdown: kramdown
theme: minima # or any other Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Author settings
author:
  name: Your Name
  email: your-email@example.com
  github: https://github.com/username

# Social media settings
twitter_username: your_twitter_username
github_username: username

# Collections
collections:
  my_collection:
    output: true

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Your Name

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include in processing
include:
  - _pages

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter_opts:
    inline_theme: monokai
    line_numbers: true

# SEO settings
seo:
  title: "My GitHub Page"
  description: "A description of my awesome GitHub Pages site."
  url: "https://username.github.io"
  twitter:
    username: your_twitter_username
    card: summary_large_image
  og:
    title: "My GitHub Page"
    type: website
    image: "/assets/images/og-image.jpg"
    url: "https://username.github.io"

# Other settings
paginate: 5
paginate_path: "/page:num/"

